name: example-swarm

data:
  sources:
    - name: arxiv
      paths:
        - "s3://ai2-llm/preprocessed/arxiv/v0_decontaminated/*.npy"
    - name: dclm
      topics:
        - name: science_math_and_technology
          paths:
            - "s3://ai2-llm/preprocessed/dclm/v0_decontaminated/science_math_and_technology/**/*.npy"
        - name: education_and_jobs
          paths:
            - "s3://ai2-llm/preprocessed/dclm/v0_decontaminated/education_and_jobs/**/*.npy"
        - name: software_development
          paths:
            - "s3://ai2-llm/preprocessed/dclm/v0_decontaminated/software_development/**/*.npy"
    - name: wikipedia
      paths:
        - "s3://ai2-llm/preprocessed/wiki/v0_decontaminated/*.npy"

priors:
  token_counts:
    arxiv: 21377485731
    "dclm:education_and_jobs": 20771836713
    "dclm:science_math_and_technology": 84526121193
    "dclm:software_development": 23878302458
    wikipedia: 3692487830

swarm:
  seed: 42
  variants: 4
  mix_temperature: 1.0
  min_strength: 0.1
  max_strength: 5.0
  minimum_weight: 0.002

max_tokens: 140000000  # e.g. 20 * 14M params * 0.5 chinchilla multiple
